name: Java CI con pruebas y notificación

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar código
      run: javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar src/Calculadora.java test/CalculadoraTest.java

    - name: Ejecutar pruebas
      run: java -cp .:src:test:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore CalculadoraTest

    - name: Notificar en Slack si falla
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"❌ Fallo en el pipeline de la Calculadora Java. Revisa las pruebas en GitHub Actions."}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}